Hotfix#21
WildCodeSchool/RMT-2203-TeamKarma-lions pull request #53
Opened 2022-04-29 13:42 UTC by gnos28

2022-04-29 13:46 UTC, ClemDSC approved these changes
ok!

2022-04-30 13:22 UTC, lchastanet requested changes

2022-04-30 13:22 UTC, lchastanet commented on frontend/src/components/FunFact.jsx
> +          {textBack2 !== null && textBack2}
First condition seems useless

2022-04-30 13:22 UTC, lchastanet commented on frontend/src/styles/Funfactlist.scss
> +    // text-align: center;
Commented code here

2022-04-30 16:12 UTC, gnos28 commented on frontend/src/components/FunFact.jsx
> +          {textBack2 !== null && textBack2}
corrected in last commit

2022-04-30 16:13 UTC, gnos28 commented on frontend/src/styles/Funfactlist.scss
> +    // text-align: center;
corrected in last commit

2022-04-30 16:14 UTC, gnos28 commented
change request done in commit [7561bc2](https://github.com/WildCodeSchool/RMT-2203-TeamKarma-lions/pull/53/commits/7561bc28dd6df82f6407710330eb2305dc564abb)

2022-05-02 08:19 UTC, lchastanet approved these changes
Top !

2022-05-02 08:19 UTC, merged