Us23 n2 yo sattelites 3 d map #41
WildCodeSchool/RMT-2203-TeamKarma-lions pull request #57
Opened 2022-05-04 15:28 UTC by gnos28

2022-05-04 15:33 UTC, PaulKip44 approved these changes
ok

2022-05-04 18:44 UTC, gnos28 commented
https://github.com/ericgio/react-bootstrap-typeahead/issues/715
please notice I got this warning reported 2 days ago on react-bootstrap-typeahead package github
let's keep an eye over this, hopefully it'll be quickly solved

2022-05-04 18:49 UTC, gnos28 commented
![image](https://user-images.githubusercontent.com/93570261/166804590-712b06e9-ad1e-4665-8079-b39516e66ba0.png)
some improvements can be done on initial loading time
- useless packages loaded (why react-calendar ??)
- 2mb coming from backend >> database should be cleaned up a bit
- earth texture coming from external source >> should be put in local
a loading component will also be added in a near future

2022-05-04 18:53 UTC, gnos28 commented
![image](https://user-images.githubusercontent.com/93570261/166805513-567d2f80-a541-4d10-be49-2b02919bbfd3.png)
known performance issue / bug :
when hovering a satellite (in order to display details in the bottom part) seems like the whole component / page ? is being re-rendered from scratch
to be investigated though...

2022-05-04 20:08 UTC, lchastanet requested changes

2022-05-04 20:08 UTC, lchastanet commented on backend/src/models/N2yoManager.js
> +}
Dead code 😄

2022-05-04 20:08 UTC, lchastanet commented on backend/src/N2yoListener.js
> +];
Please put data in dedicated file

2022-05-04 20:34 UTC, gnos28 commented on backend/src/models/N2yoManager.js
> +}
already corrected in last commit

2022-05-04 20:50 UTC, gnos28 commented on backend/src/N2yoListener.js
> +];
done in last commit

2022-05-05 07:06 UTC, lchastanet approved these changes
Ok, nickel

2022-05-05 07:11 UTC, merged