Hotfix#70 experimental
WildCodeSchool/RMT-2203-TeamKarma-lions pull request #91
Opened 2022-05-10 15:51 UTC by gnos28

à revoir ensemble c'est une galère

2022-05-10 16:05 UTC, PaulKip44 approved these changes
"experimental"

2022-05-11 06:37 UTC, lchastanet requested changes

2022-05-11 06:37 UTC, lchastanet commented on frontend/src/components/Satellites/GlobeContainer.jsx
> +      console.warn(tooltip); // juste pour la démo !!
Would it block the team ?

2022-05-11 06:37 UTC, lchastanet commented on frontend/src/components/Satellites/HoverInfo.jsx
> +    // }
Same here

2022-05-11 06:37 UTC, lchastanet commented on frontend/src/pages/Satellites.jsx
> +      .get(`http://localhost:5000/api/n2yo/catbysatid`, { signal })
This will never work when deployed

2022-05-11 08:33 UTC, gnos28 commented
latest commit is ok

2022-05-11 09:38 UTC, gnos28 commented
j'ai re git pull push

2022-05-11 10:18 UTC, lchastanet approved these changes
Ok

2022-05-11 10:18 UTC, merged